apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tp2-pvc
  namespace: viniciusabel
spec:
  storageClassName: default-storage-class-viniciusabel
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: project2-pv-viniciusabel